// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SentimentalAnalysisML.Stemmer")>]
[<assembly: AssemblyProductAttribute("SentimentalAnalysisML.Stemmer")>]
[<assembly: AssemblyDescriptionAttribute("An English (Porter2) stemming F# implementation.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SentimentalAnalysisML.Stemmer"
    let [<Literal>] AssemblyProduct = "SentimentalAnalysisML.Stemmer"
    let [<Literal>] AssemblyDescription = "An English (Porter2) stemming F# implementation."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
